version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./mysql/db-volume:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
    environment:
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
      
